/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiAdsUpdateRouteImport } from './routes/api/ads.update'
import { Route as ApiAdsRegenerateRouteImport } from './routes/api/ads.regenerate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsUpdateRoute = ApiAdsUpdateRouteImport.update({
  id: '/api/ads/update',
  path: '/api/ads/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsRegenerateRoute = ApiAdsRegenerateRouteImport.update({
  id: '/api/ads/regenerate',
  path: '/api/ads/regenerate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/ads/regenerate': typeof ApiAdsRegenerateRoute
  '/api/ads/update': typeof ApiAdsUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/ads/regenerate': typeof ApiAdsRegenerateRoute
  '/api/ads/update': typeof ApiAdsUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/ads/regenerate': typeof ApiAdsRegenerateRoute
  '/api/ads/update': typeof ApiAdsUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/jobs' | '/api/ads/regenerate' | '/api/ads/update'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/jobs' | '/api/ads/regenerate' | '/api/ads/update'
  id: '__root__' | '/' | '/api/jobs' | '/api/ads/regenerate' | '/api/ads/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiAdsRegenerateRoute: typeof ApiAdsRegenerateRoute
  ApiAdsUpdateRoute: typeof ApiAdsUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/update': {
      id: '/api/ads/update'
      path: '/api/ads/update'
      fullPath: '/api/ads/update'
      preLoaderRoute: typeof ApiAdsUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/regenerate': {
      id: '/api/ads/regenerate'
      path: '/api/ads/regenerate'
      fullPath: '/api/ads/regenerate'
      preLoaderRoute: typeof ApiAdsRegenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiAdsRegenerateRoute: ApiAdsRegenerateRoute,
  ApiAdsUpdateRoute: ApiAdsUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
